# Repo languages
languages:
- python

# Max depth is actually 2, we set this to 3 just in case
# max depth increase in the future.
#
# Max depth refers to nesting of folders containing code.
component_depth: 3
