FILTERS = {
    "sorting": {
        "relevance_highest": None,
        "price_from_lowest": "order=p",
        "price_from_highest": "order=pd",
        "price_with_delivery_from_lowest": "order=d",
        "price_with_delivery_from_highest": "order=dd",
        "popularity_highest": "order=qd",
        "time_to_end_least": "order=t",
        "time_added_latest": "order=n",
    },
    "smart_free_shipping": "allegro-smart-standard=1",
    "product_condition": {
        "new": "stan=nowe",
        "used": "stan=używane",
        "incomplete_set": "stan=niepełny komplet",
        "new_without_tags": "stan=nowe bez metki",
        "new_with_defect": "stan=nowe z defektem",
        "after_return": "stan=po zwrocie",
        "aftermarket": "stan=powystawowe",
        "regenerated": "stan=regenerowane",
        "damaged": "stan=uszkodzone",
        "refurbished": "stan=odnowione przez sprzedawcę",
        "for_renovation": "stan=do renowacji",
        "not_requiring_renovation": "stan=niewymagające renowacji",
    },
    "offer_type": {
        "buy_now": "offerTypeBuyNow=1",
        "auction": "offerTypeAuction=2",
        "advertisement": "offerTypeAdvert=3",
    },
    "price_min": lambda value: f"price_from={str(value)}",
    "price_max": lambda value: f"price_to={str(value)}",
    "delivery_time": {
        "today": "delivery_time=today",
        "one_day": "delivery_time=one_day",
        "two_day": "delivery_time=two_days",
    },
    "delivery_methods": {
        "courier": "dostawa-kurier=1",
        "inpost_parcel_locker": "dostawa-paczkomaty-inpost=1",
        "overseas_delivery": "dostawa-dostawa-za-granice=1",
        "pickup_at_the_point": "dostawa-odbior-w-punkcie=1",
        "letter": "dostawa-list=1",
        "package": "dostawa-paczka=1",
        "pickup": "dostawa-odbior-osobisty=1",
        "email": "dostawa-przesylka-elektroniczna=1",
    },
    "delivery_options": {
        "free_shipping": "freeShipping=1",
        "free_return": "freeReturn=1",
    },
    "city": lambda value: f"city={str(value)}",
    "voivodeship": {
        "dolnośląskie": "state=1",
        "kujawsko_pomorskie": "state=2",
        "lubelskie": "state=3",
        "lubuskie": "state=4",
        "łódzkie": "state=5",
        "małopolskie": "state=6",
        "mazowieckie": "state=7",
        "opolskie": "state=8",
        "podkarpackie": "state=9",
        "podlaskie": "state=10",
        "pomorskie": "state=11",
        "śląskie": "state=12",
        "świętokrzyskie": "state=13",
        "warmińsko_mazurskie": "state=14",
        "wielkopolskie": "state=15",
        "zachodniopomorskie": "state=16",
    },
    "product_rating": {
        "from4.9": "ocena-produktu=od-4.9",
        "from4.8": "ocena-produktu=od-4.8",
        "from4.5": "ocena-produktu=od-4.5",
    },
    "vat_invoice": "vat_invoice=1",
    "allegro_programs": {
        "allegro_coins": "monety=1",
        "brand_zone": "sm=1",
        "great_seller": "super-sprzedawca=1",
        "allegro_charity": "cel-charytatywny=wszystkie",
    },
    "occasions": {
        "installments_of_zero_percent": "raty-zero=1",
        "opportunity_zone": "ok=1",
        "great_price": "price-subsidy=1",
    },
}
